/* ============================================================
   VerbiFox · Temas de Inglés 1° a 6° básico
   Contenido original, alineado a la progresión escolar de inglés
   del currículo chileno (inglés se enseña formalmente desde 5°).
   Estructura: TEMAS_INGLES[curso] = [ {id,nombre,emoji,oa,intro,palabras:[{en,es,e}],frases:[{en,es}]} ]
   ============================================================ */
window.TEMAS_INGLES = {
"1": [
  { id:'saludos1', nombre:'Saludos', emoji:'👋', oa:'Saludar y despedirse',
    intro:'Hello! · Bye!',
    palabras:[{en:'Hello',es:'Hola',e:'👋'},{en:'Hi',es:'Hola (informal)',e:'🙂'},{en:'Bye',es:'Chao',e:'👋'},{en:'Good morning',es:'Buenos días',e:'🌅'},{en:'Good night',es:'Buenas noches',e:'🌙'},{en:'Please',es:'Por favor',e:'🙏'},{en:'Thank you',es:'Gracias',e:'😊'},{en:'Yes',es:'Sí',e:'✅'},{en:'No',es:'No',e:'❌'}],
    frases:[{en:'Hello! How are you?',es:'¡Hola! ¿Cómo estás?'},{en:"I'm fine, thank you.",es:'Estoy bien, gracias.'}] },
  { id:'colores1', nombre:'Colores', emoji:'🎨', oa:'Nombrar colores',
    intro:'What color is it?',
    palabras:[{en:'red',es:'rojo',e:'🔴'},{en:'blue',es:'azul',e:'🔵'},{en:'yellow',es:'amarillo',e:'🟡'},{en:'green',es:'verde',e:'🟢'},{en:'orange',es:'naranjo',e:'🟠'},{en:'purple',es:'morado',e:'🟣'},{en:'black',es:'negro',e:'⚫'},{en:'white',es:'blanco',e:'⚪'},{en:'pink',es:'rosado',e:'🌸'},{en:'brown',es:'café',e:'🟤'}],
    frases:[{en:'The apple is red.',es:'La manzana es roja.'},{en:'My favorite color is blue.',es:'Mi color favorito es el azul.'}] },
  { id:'numeros1', nombre:'Números 1 a 10', emoji:'🔢', oa:'Contar hasta 10',
    intro:'Count with me!',
    palabras:[{en:'one',es:'uno (1)',e:'1️⃣'},{en:'two',es:'dos (2)',e:'2️⃣'},{en:'three',es:'tres (3)',e:'3️⃣'},{en:'four',es:'cuatro (4)',e:'4️⃣'},{en:'five',es:'cinco (5)',e:'5️⃣'},{en:'six',es:'seis (6)',e:'6️⃣'},{en:'seven',es:'siete (7)',e:'7️⃣'},{en:'eight',es:'ocho (8)',e:'8️⃣'},{en:'nine',es:'nueve (9)',e:'9️⃣'},{en:'ten',es:'diez (10)',e:'🔟'}],
    frases:[{en:'I have two hands.',es:'Tengo dos manos.'},{en:'Count to ten!',es:'¡Cuenta hasta diez!'}] },
  { id:'animales1', nombre:'Animales', emoji:'🐶', oa:'Nombrar animales',
    intro:'What animal is it?',
    palabras:[{en:'dog',es:'perro',e:'🐶'},{en:'cat',es:'gato',e:'🐱'},{en:'bird',es:'pájaro',e:'🐦'},{en:'fish',es:'pez',e:'🐟'},{en:'cow',es:'vaca',e:'🐮'},{en:'horse',es:'caballo',e:'🐴'},{en:'duck',es:'pato',e:'🦆'},{en:'rabbit',es:'conejo',e:'🐰'},{en:'lion',es:'león',e:'🦁'},{en:'bear',es:'oso',e:'🐻'}],
    frases:[{en:'The dog is big.',es:'El perro es grande.'},{en:'I like cats.',es:'Me gustan los gatos.'}] },
  { id:'sala1', nombre:'En la sala', emoji:'🏫', oa:'Objetos de la sala',
    intro:'This is a book.',
    palabras:[{en:'book',es:'libro',e:'📖'},{en:'pencil',es:'lápiz',e:'✏️'},{en:'chair',es:'silla',e:'🪑'},{en:'table',es:'mesa',e:'🪵'},{en:'bag',es:'bolso',e:'🎒'},{en:'door',es:'puerta',e:'🚪'},{en:'window',es:'ventana',e:'🪟'},{en:'crayon',es:'crayón',e:'🖍️'}],
    frases:[{en:'This is my pencil.',es:'Este es mi lápiz.'},{en:'Open your book.',es:'Abre tu libro.'}] },
  { id:'cuerpo1', nombre:'Mi cuerpo', emoji:'🧒', oa:'Partes del cuerpo',
    intro:'Touch your head!',
    palabras:[{en:'head',es:'cabeza',e:'👦'},{en:'hand',es:'mano',e:'✋'},{en:'foot',es:'pie',e:'🦶'},{en:'eye',es:'ojo',e:'👁️'},{en:'ear',es:'oreja',e:'👂'},{en:'nose',es:'nariz',e:'👃'},{en:'mouth',es:'boca',e:'👄'},{en:'hair',es:'pelo',e:'💇'}],
    frases:[{en:'Touch your nose.',es:'Tócate la nariz.'},{en:'I have two eyes.',es:'Tengo dos ojos.'}] }
],
"2": [
  { id:'numeros2', nombre:'Números 11 a 20', emoji:'🔢', oa:'Contar hasta 20',
    intro:'eleven, twelve, thirteen…',
    palabras:[{en:'eleven',es:'once (11)',e:'🔢'},{en:'twelve',es:'doce (12)',e:'🔢'},{en:'thirteen',es:'trece (13)',e:'🔢'},{en:'fourteen',es:'catorce (14)',e:'🔢'},{en:'fifteen',es:'quince (15)',e:'🔢'},{en:'sixteen',es:'dieciséis (16)',e:'🔢'},{en:'seventeen',es:'diecisiete (17)',e:'🔢'},{en:'eighteen',es:'dieciocho (18)',e:'🔢'},{en:'nineteen',es:'diecinueve (19)',e:'🔢'},{en:'twenty',es:'veinte (20)',e:'🔢'}],
    frases:[{en:'I am eight years old.',es:'Tengo ocho años.'},{en:'There are twenty students.',es:'Hay veinte estudiantes.'}] },
  { id:'comida2', nombre:'Comida', emoji:'🍎', oa:'Nombrar comidas',
    intro:'I like apples.',
    palabras:[{en:'apple',es:'manzana',e:'🍎'},{en:'banana',es:'plátano',e:'🍌'},{en:'bread',es:'pan',e:'🍞'},{en:'milk',es:'leche',e:'🥛'},{en:'egg',es:'huevo',e:'🥚'},{en:'water',es:'agua',e:'💧'},{en:'rice',es:'arroz',e:'🍚'},{en:'cheese',es:'queso',e:'🧀'},{en:'cake',es:'torta',e:'🍰'},{en:'juice',es:'jugo',e:'🧃'}],
    frases:[{en:'I like bread and cheese.',es:'Me gusta el pan con queso.'},{en:'I want water, please.',es:'Quiero agua, por favor.'}] },
  { id:'familia2', nombre:'La familia', emoji:'👨‍👩‍👧', oa:'Miembros de la familia',
    intro:'This is my family.',
    palabras:[{en:'mom',es:'mamá',e:'👩'},{en:'dad',es:'papá',e:'👨'},{en:'sister',es:'hermana',e:'👧'},{en:'brother',es:'hermano',e:'👦'},{en:'baby',es:'bebé',e:'👶'},{en:'grandma',es:'abuela',e:'👵'},{en:'grandpa',es:'abuelo',e:'👴'}],
    frases:[{en:'This is my mom.',es:'Esta es mi mamá.'},{en:'I love my family.',es:'Amo a mi familia.'}] },
  { id:'sentimientos2', nombre:'Sentimientos', emoji:'😊', oa:'Expresar sentimientos',
    intro:'I am happy!',
    palabras:[{en:'happy',es:'feliz',e:'😄'},{en:'sad',es:'triste',e:'😢'},{en:'angry',es:'enojado',e:'😠'},{en:'tired',es:'cansado',e:'😴'},{en:'hungry',es:'con hambre',e:'😋'},{en:'scared',es:'asustado',e:'😨'}],
    frases:[{en:'I am happy today.',es:'Hoy estoy feliz.'},{en:'Are you tired?',es:'¿Estás cansado?'}] },
  { id:'casa2', nombre:'Mi casa', emoji:'🏠', oa:'Partes de la casa',
    intro:'This is the kitchen.',
    palabras:[{en:'house',es:'casa',e:'🏠'},{en:'kitchen',es:'cocina',e:'🍳'},{en:'bedroom',es:'dormitorio',e:'🛏️'},{en:'bathroom',es:'baño',e:'🛁'},{en:'living room',es:'living',e:'🛋️'},{en:'garden',es:'jardín',e:'🌷'},{en:'door',es:'puerta',e:'🚪'},{en:'bed',es:'cama',e:'🛏️'}],
    frases:[{en:'My house is big.',es:'Mi casa es grande.'},{en:'The cat is in the kitchen.',es:'El gato está en la cocina.'}] },
  { id:'dias2', nombre:'Días de la semana', emoji:'📅', oa:'Días de la semana',
    intro:'Today is Monday.',
    palabras:[{en:'Monday',es:'lunes',e:'📅'},{en:'Tuesday',es:'martes',e:'📅'},{en:'Wednesday',es:'miércoles',e:'📅'},{en:'Thursday',es:'jueves',e:'📅'},{en:'Friday',es:'viernes',e:'📅'},{en:'Saturday',es:'sábado',e:'🎉'},{en:'Sunday',es:'domingo',e:'☀️'}],
    frases:[{en:'Today is Friday.',es:'Hoy es viernes.'},{en:'I play on Saturday.',es:'Juego el sábado.'}] }
],
"3": [
  { id:'clima3', nombre:'El clima', emoji:'☀️', oa:'Describir el clima',
    intro:"How's the weather?",
    palabras:[{en:'sunny',es:'soleado',e:'☀️'},{en:'rainy',es:'lluvioso',e:'🌧️'},{en:'cloudy',es:'nublado',e:'☁️'},{en:'windy',es:'ventoso',e:'💨'},{en:'snowy',es:'nevado',e:'❄️'},{en:'hot',es:'caluroso',e:'🥵'},{en:'cold',es:'frío',e:'🥶'},{en:'rainbow',es:'arcoíris',e:'🌈'}],
    frases:[{en:"It's sunny today.",es:'Hoy está soleado.'},{en:"It's cold in winter.",es:'Hace frío en invierno.'}] },
  { id:'bebidas3', nombre:'Comidas y bebidas', emoji:'🍽️', oa:'Comidas y bebidas',
    intro:'I eat fruit. I drink water.',
    palabras:[{en:'chicken',es:'pollo',e:'🍗'},{en:'fish',es:'pescado',e:'🐟'},{en:'soup',es:'sopa',e:'🍲'},{en:'salad',es:'ensalada',e:'🥗'},{en:'fruit',es:'fruta',e:'🍓'},{en:'vegetables',es:'verduras',e:'🥦'},{en:'tea',es:'té',e:'🍵'},{en:'coffee',es:'café',e:'☕'},{en:'ice cream',es:'helado',e:'🍦'},{en:'candy',es:'dulce',e:'🍬'}],
    frases:[{en:'I eat vegetables every day.',es:'Como verduras todos los días.'},{en:'Do you like ice cream?',es:'¿Te gusta el helado?'}] },
  { id:'acciones3', nombre:'Verbos de acción', emoji:'🏃', oa:'Verbos comunes',
    intro:'I run. I jump.',
    palabras:[{en:'run',es:'correr',e:'🏃'},{en:'jump',es:'saltar',e:'🤸'},{en:'walk',es:'caminar',e:'🚶'},{en:'swim',es:'nadar',e:'🏊'},{en:'sing',es:'cantar',e:'🎤'},{en:'dance',es:'bailar',e:'💃'},{en:'read',es:'leer',e:'📖'},{en:'write',es:'escribir',e:'✍️'},{en:'draw',es:'dibujar',e:'🖍️'},{en:'play',es:'jugar',e:'⚽'}],
    frases:[{en:'I can swim.',es:'Sé nadar.'},{en:'She likes to draw.',es:'A ella le gusta dibujar.'}] },
  { id:'cuerpo3', nombre:'El cuerpo', emoji:'🧍', oa:'Partes del cuerpo',
    intro:'This is my arm.',
    palabras:[{en:'arm',es:'brazo',e:'💪'},{en:'leg',es:'pierna',e:'🦵'},{en:'hand',es:'mano',e:'✋'},{en:'finger',es:'dedo',e:'👆'},{en:'knee',es:'rodilla',e:'🦵'},{en:'tooth',es:'diente',e:'🦷'},{en:'tongue',es:'lengua',e:'👅'},{en:'heart',es:'corazón',e:'❤️'}],
    frases:[{en:'My leg hurts.',es:'Me duele la pierna.'},{en:'Wash your hands.',es:'Lávate las manos.'}] },
  { id:'transporte3', nombre:'Transporte', emoji:'🚗', oa:'Medios de transporte',
    intro:'I go by bus.',
    palabras:[{en:'car',es:'auto',e:'🚗'},{en:'bus',es:'micro/bus',e:'🚌'},{en:'bike',es:'bicicleta',e:'🚲'},{en:'train',es:'tren',e:'🚆'},{en:'plane',es:'avión',e:'✈️'},{en:'boat',es:'bote',e:'⛵'},{en:'truck',es:'camión',e:'🚚'},{en:'motorcycle',es:'moto',e:'🏍️'}],
    frases:[{en:'I go to school by bus.',es:'Voy al colegio en micro.'},{en:'The plane is fast.',es:'El avión es rápido.'}] },
  { id:'meses3', nombre:'Los meses', emoji:'📆', oa:'Meses del año',
    intro:'My birthday is in May.',
    palabras:[{en:'January',es:'enero',e:'📆'},{en:'February',es:'febrero',e:'📆'},{en:'March',es:'marzo',e:'📆'},{en:'April',es:'abril',e:'📆'},{en:'May',es:'mayo',e:'📆'},{en:'June',es:'junio',e:'📆'},{en:'July',es:'julio',e:'📆'},{en:'September',es:'septiembre',e:'📆'},{en:'December',es:'diciembre',e:'🎄'}],
    frases:[{en:'My birthday is in July.',es:'Mi cumpleaños es en julio.'},{en:'School starts in March.',es:'El colegio empieza en marzo.'}] }
],
"4": [
  { id:'hora4', nombre:'La hora', emoji:'⏰', oa:'Decir la hora',
    intro:'What time is it?',
    palabras:[{en:"o'clock",es:'en punto',e:'🕐'},{en:'half past',es:'y media',e:'🕜'},{en:'quarter past',es:'y cuarto',e:'🕒'},{en:'quarter to',es:'cuarto para',e:'🕘'},{en:'hour',es:'hora',e:'⏰'},{en:'minute',es:'minuto',e:'⏱️'},{en:'early',es:'temprano',e:'🌅'},{en:'late',es:'tarde',e:'🌙'}],
    frases:[{en:"It's four o'clock.",es:'Son las cuatro en punto.'},{en:"It's half past nine.",es:'Son las nueve y media.'}] },
  { id:'oficios4', nombre:'Oficios', emoji:'💼', oa:'Ocupaciones',
    intro:'She is a doctor.',
    palabras:[{en:'doctor',es:'doctor(a)',e:'🧑‍⚕️'},{en:'teacher',es:'profesor(a)',e:'🧑‍🏫'},{en:'police officer',es:'policía',e:'👮'},{en:'firefighter',es:'bombero',e:'🧑‍🚒'},{en:'cook',es:'cocinero(a)',e:'🧑‍🍳'},{en:'driver',es:'conductor(a)',e:'🚗'},{en:'dentist',es:'dentista',e:'🦷'},{en:'vet',es:'veterinario(a)',e:'🐾'}],
    frases:[{en:'My dad is a driver.',es:'Mi papá es conductor.'},{en:'I want to be a vet.',es:'Quiero ser veterinario.'}] },
  { id:'deportes4', nombre:'Deportes y hobbies', emoji:'⚽', oa:'Deportes y pasatiempos',
    intro:'I play soccer.',
    palabras:[{en:'soccer',es:'fútbol',e:'⚽'},{en:'basketball',es:'básquetbol',e:'🏀'},{en:'tennis',es:'tenis',e:'🎾'},{en:'swimming',es:'natación',e:'🏊'},{en:'running',es:'correr',e:'🏃'},{en:'painting',es:'pintar',e:'🎨'},{en:'reading',es:'leer',e:'📚'},{en:'video games',es:'videojuegos',e:'🎮'}],
    frases:[{en:'I play basketball on Mondays.',es:'Juego básquetbol los lunes.'},{en:'My hobby is painting.',es:'Mi pasatiempo es pintar.'}] },
  { id:'ciudad4', nombre:'Lugares del pueblo', emoji:'🏙️', oa:'Lugares de la ciudad',
    intro:'The park is near.',
    palabras:[{en:'park',es:'parque',e:'🏞️'},{en:'school',es:'colegio',e:'🏫'},{en:'hospital',es:'hospital',e:'🏥'},{en:'store/shop',es:'tienda',e:'🏬'},{en:'library',es:'biblioteca',e:'📚'},{en:'market',es:'mercado',e:'🧺'},{en:'church',es:'iglesia',e:'⛪'},{en:'street',es:'calle',e:'🛣️'}],
    frases:[{en:'The library is next to the school.',es:'La biblioteca está al lado del colegio.'},{en:'Where is the park?',es:'¿Dónde está el parque?'}] },
  { id:'rutinas4', nombre:'Mi rutina (present simple)', emoji:'🔤', oa:'Rutinas diarias',
    intro:'I wake up at 7. I go to school.',
    palabras:[{en:'wake up',es:'despertar',e:'⏰'},{en:'get up',es:'levantarse',e:'🛏️'},{en:'have breakfast',es:'desayunar',e:'🥣'},{en:'brush teeth',es:'cepillar dientes',e:'🪥'},{en:'go to school',es:'ir al colegio',e:'🎒'},{en:'do homework',es:'hacer tareas',e:'📝'},{en:'have lunch',es:'almorzar',e:'🍽️'},{en:'go to bed',es:'acostarse',e:'😴'}],
    frases:[{en:'I wake up at seven.',es:'Me despierto a las siete.'},{en:'She does her homework.',es:'Ella hace sus tareas.'}] },
  { id:'gustos4', nombre:'Gustos y comida', emoji:'🍕', oa:'Expresar gustos',
    intro:'I like pizza. I don\'t like onions.',
    palabras:[{en:'pizza',es:'pizza',e:'🍕'},{en:'hamburger',es:'hamburguesa',e:'🍔'},{en:'french fries',es:'papas fritas',e:'🍟'},{en:'chocolate',es:'chocolate',e:'🍫'},{en:'popcorn',es:'cabritas',e:'🍿'},{en:'onion',es:'cebolla',e:'🧅'},{en:'tomato',es:'tomate',e:'🍅'},{en:'carrot',es:'zanahoria',e:'🥕'}],
    frases:[{en:'I like pizza.',es:'Me gusta la pizza.'},{en:"I don't like onions.",es:'No me gustan las cebollas.'}] }
],
"5": [
  { id:'saludos', nombre:'Saludos e información personal', emoji:'👋', oa:'Dar y pedir información personal · saludar y despedirse',
    intro:"What's your name? · How old are you? · Where are you from?",
    palabras:[{en:'Hello / Hi',es:'Hola',e:'👋'},{en:'Goodbye / Bye',es:'Adiós',e:'👋'},{en:'Good morning',es:'Buenos días',e:'🌅'},{en:'Good afternoon',es:'Buenas tardes',e:'🌇'},{en:'name',es:'nombre',e:'🪪'},{en:'age',es:'edad',e:'🎂'},{en:'Nice to meet you',es:'Mucho gusto',e:'🤝'},{en:'Thank you',es:'Gracias',e:'🙏'},{en:'Please',es:'Por favor',e:'🙂'},{en:'Sorry',es:'Perdón / Lo siento',e:'😔'}],
    frases:[{en:"What's your name?",es:'¿Cómo te llamas?'},{en:'My name is Martín.',es:'Me llamo Martín.'},{en:'How old are you?',es:'¿Cuántos años tienes?'},{en:"I'm eleven years old.",es:'Tengo once años.'},{en:'Where are you from?',es:'¿De dónde eres?'},{en:"I'm from Chile.",es:'Soy de Chile.'}] },
  { id:'numeros', nombre:'Números y la hora', emoji:'🔢', oa:'Números hasta 1000 · pedir y decir la hora',
    intro:"What time is it? · It's seven o'clock.",
    palabras:[{en:'ten',es:'diez (10)',e:'🔟'},{en:'twenty',es:'veinte (20)',e:'🔢'},{en:'fifty',es:'cincuenta (50)',e:'🔢'},{en:'one hundred',es:'cien (100)',e:'💯'},{en:'one thousand',es:'mil (1000)',e:'🔢'},{en:"o'clock",es:'en punto',e:'🕐'},{en:'half past',es:'y media',e:'🕜'},{en:'quarter past',es:'y cuarto',e:'🕒'},{en:'morning',es:'mañana',e:'🌅'},{en:'night',es:'noche',e:'🌙'}],
    frases:[{en:'What time is it?',es:'¿Qué hora es?'},{en:"It's seven o'clock.",es:'Son las siete en punto.'},{en:"It's half past three.",es:'Son las tres y media.'},{en:'I have twenty pencils.',es:'Tengo veinte lápices.'}] },
  { id:'familia', nombre:'La familia', emoji:'👨‍👩‍👧', oa:'Describir personas · posesiones (my, your, his, her)',
    intro:'This is my family. · She is my sister.',
    palabras:[{en:'mother / mom',es:'madre / mamá',e:'👩'},{en:'father / dad',es:'padre / papá',e:'👨'},{en:'brother',es:'hermano',e:'👦'},{en:'sister',es:'hermana',e:'👧'},{en:'grandmother',es:'abuela',e:'👵'},{en:'grandfather',es:'abuelo',e:'👴'},{en:'baby',es:'bebé',e:'👶'},{en:'aunt',es:'tía',e:'👩'},{en:'uncle',es:'tío',e:'👨'},{en:'cousin',es:'primo / prima',e:'🧒'}],
    frases:[{en:'This is my mother.',es:'Esta es mi madre.'},{en:'He is my brother.',es:'Él es mi hermano.'},{en:'Her name is Ana.',es:'Ella se llama Ana.'},{en:'I have two sisters.',es:'Tengo dos hermanas.'}] },
  { id:'escuela', nombre:'La escuela', emoji:'🏫', oa:'Vocabulario cotidiano · there is / there are',
    intro:'There is a book. · There are three pencils.',
    palabras:[{en:'teacher',es:'profesor(a)',e:'🧑‍🏫'},{en:'student',es:'estudiante',e:'🧑‍🎓'},{en:'book',es:'libro',e:'📖'},{en:'pencil',es:'lápiz',e:'✏️'},{en:'notebook',es:'cuaderno',e:'📓'},{en:'eraser',es:'goma de borrar',e:'🧽'},{en:'ruler',es:'regla',e:'📏'},{en:'backpack',es:'mochila',e:'🎒'},{en:'classroom',es:'sala de clases',e:'🚪'},{en:'blackboard',es:'pizarra',e:'⬛'}],
    frases:[{en:'There is a teacher.',es:'Hay un(a) profesor(a).'},{en:'There are five books.',es:'Hay cinco libros.'},{en:'This is my backpack.',es:'Esta es mi mochila.'},{en:'My favorite subject is math.',es:'Mi ramo favorito es matemática.'}] },
  { id:'ocupaciones', nombre:'Ocupaciones', emoji:'💼', oa:'Describir ocupaciones · What does he do?',
    intro:'She is a doctor. · He is a firefighter.',
    palabras:[{en:'doctor',es:'doctor(a)',e:'🧑‍⚕️'},{en:'teacher',es:'profesor(a)',e:'🧑‍🏫'},{en:'firefighter',es:'bombero(a)',e:'🧑‍🚒'},{en:'police officer',es:'policía',e:'👮'},{en:'cook / chef',es:'cocinero(a)',e:'🧑‍🍳'},{en:'farmer',es:'agricultor(a)',e:'🧑‍🌾'},{en:'pilot',es:'piloto',e:'🧑‍✈️'},{en:'engineer',es:'ingeniero(a)',e:'🧑‍🔧'},{en:'artist',es:'artista',e:'🧑‍🎨'},{en:'singer',es:'cantante',e:'🧑‍🎤'}],
    frases:[{en:'She is a doctor.',es:'Ella es doctora.'},{en:'What does he do?',es:'¿A qué se dedica él?'},{en:'I want to be a pilot.',es:'Quiero ser piloto.'}] },
  { id:'emociones', nombre:'Emociones y personalidad', emoji:'😊', oa:'Expresar estados emocionales · How do you feel?',
    intro:'I am happy. · He is tired.',
    palabras:[{en:'happy',es:'feliz',e:'😄'},{en:'sad',es:'triste',e:'😢'},{en:'angry',es:'enojado(a)',e:'😠'},{en:'tired',es:'cansado(a)',e:'😴'},{en:'scared',es:'asustado(a)',e:'😨'},{en:'excited',es:'emocionado(a)',e:'🤩'},{en:'hungry',es:'con hambre',e:'😋'},{en:'shy',es:'tímido(a)',e:'😳'},{en:'kind',es:'amable',e:'😇'},{en:'funny',es:'gracioso(a)',e:'🤣'}],
    frases:[{en:'How do you feel?',es:'¿Cómo te sientes?'},{en:'I am happy today.',es:'Hoy estoy feliz.'},{en:'She is very kind.',es:'Ella es muy amable.'}] },
  { id:'ropa', nombre:'La ropa', emoji:'👕', oa:'Describir objetos · I am wearing…',
    intro:"I'm wearing a red t-shirt.",
    palabras:[{en:'t-shirt',es:'polera',e:'👕'},{en:'pants',es:'pantalones',e:'👖'},{en:'dress',es:'vestido',e:'👗'},{en:'shoes',es:'zapatos',e:'👟'},{en:'jacket',es:'chaqueta',e:'🧥'},{en:'hat',es:'gorro / sombrero',e:'🧢'},{en:'socks',es:'calcetines',e:'🧦'},{en:'skirt',es:'falda',e:'👗'},{en:'gloves',es:'guantes',e:'🧤'},{en:'scarf',es:'bufanda',e:'🧣'}],
    frases:[{en:"I'm wearing a blue jacket.",es:'Llevo una chaqueta azul.'},{en:'She is wearing a red dress.',es:'Ella lleva un vestido rojo.'},{en:'My shoes are new.',es:'Mis zapatos son nuevos.'}] },
  { id:'acciones', nombre:'Acciones ahora (present continuous)', emoji:'🏃', oa:'Describir acciones presentes · He is reading',
    intro:'Estructura: subject + is/are + verb-ing.',
    palabras:[{en:'reading',es:'leyendo',e:'📖'},{en:'writing',es:'escribiendo',e:'✍️'},{en:'playing',es:'jugando',e:'⚽'},{en:'eating',es:'comiendo',e:'🍎'},{en:'drinking',es:'bebiendo',e:'🥤'},{en:'running',es:'corriendo',e:'🏃'},{en:'sleeping',es:'durmiendo',e:'😴'},{en:'singing',es:'cantando',e:'🎤'},{en:'dancing',es:'bailando',e:'💃'},{en:'studying',es:'estudiando',e:'📚'}],
    frases:[{en:'He is reading a book.',es:'Él está leyendo un libro.'},{en:'They are playing soccer.',es:'Ellos están jugando fútbol.'},{en:'I am studying English.',es:'Estoy estudiando inglés.'}] },
  { id:'lugares', nombre:'Lugares y posición', emoji:'📍', oa:'Describir lugares y posición · preposiciones',
    intro:'The cat is under the table.',
    palabras:[{en:'in',es:'en / dentro',e:'📦'},{en:'on',es:'sobre / encima',e:'⬆️'},{en:'under',es:'debajo',e:'⬇️'},{en:'next to',es:'al lado de',e:'↔️'},{en:'behind',es:'detrás',e:'🔙'},{en:'in front of',es:'delante de',e:'🔜'},{en:'park',es:'parque',e:'🏞️'},{en:'school',es:'colegio',e:'🏫'},{en:'house',es:'casa',e:'🏠'},{en:'hospital',es:'hospital',e:'🏥'}],
    frases:[{en:'The ball is under the chair.',es:'La pelota está debajo de la silla.'},{en:'The dog is next to the door.',es:'El perro está al lado de la puerta.'},{en:'Where is the book?',es:'¿Dónde está el libro?'}] },
  { id:'clima', nombre:'El clima', emoji:'☀️', oa:'Describir el clima · How is the weather?',
    intro:"How's the weather? · It's sunny.",
    palabras:[{en:'sunny',es:'soleado',e:'☀️'},{en:'rainy',es:'lluvioso',e:'🌧️'},{en:'cloudy',es:'nublado',e:'☁️'},{en:'windy',es:'ventoso',e:'💨'},{en:'snowy',es:'nevado',e:'❄️'},{en:'hot',es:'caluroso',e:'🥵'},{en:'cold',es:'frío',e:'🥶'},{en:'warm',es:'templado',e:'🌤️'},{en:'storm',es:'tormenta',e:'⛈️'},{en:'rainbow',es:'arcoíris',e:'🌈'}],
    frases:[{en:"How's the weather today?",es:'¿Cómo está el clima hoy?'},{en:"It's sunny and warm.",es:'Está soleado y templado.'},{en:"It's cold in winter.",es:'Hace frío en invierno.'}] }
],
"6": [
  { id:'pasado6', nombre:'Acciones pasadas (past simple)', emoji:'⏮️', oa:'Describir acciones pasadas',
    intro:'Yesterday I played. She went home.',
    palabras:[{en:'played',es:'jugué/jugó',e:'⚽'},{en:'watched',es:'vi/vio',e:'📺'},{en:'visited',es:'visité/visitó',e:'🏛️'},{en:'went',es:'fui/fue',e:'🚶'},{en:'ate',es:'comí/comió',e:'🍽️'},{en:'saw',es:'vi/vio',e:'👀'},{en:'made',es:'hice/hizo',e:'🛠️'},{en:'yesterday',es:'ayer',e:'📅'},{en:'last week',es:'la semana pasada',e:'🗓️'}],
    frases:[{en:'Yesterday I played soccer.',es:'Ayer jugué fútbol.'},{en:'She went to the park.',es:'Ella fue al parque.'},{en:'We ate pizza last night.',es:'Comimos pizza anoche.'}] },
  { id:'futuro6', nombre:'Planes (going to)', emoji:'🔜', oa:'Hablar de planes futuros',
    intro:"I'm going to travel.",
    palabras:[{en:'going to',es:'ir a (futuro)',e:'🔜'},{en:'travel',es:'viajar',e:'✈️'},{en:'study',es:'estudiar',e:'📚'},{en:'visit',es:'visitar',e:'🏛️'},{en:'tomorrow',es:'mañana',e:'📅'},{en:'next year',es:'el próximo año',e:'🗓️'},{en:'weekend',es:'fin de semana',e:'🎉'},{en:'vacation',es:'vacaciones',e:'🏖️'}],
    frases:[{en:"I'm going to study tonight.",es:'Voy a estudiar esta noche.'},{en:'We are going to travel next year.',es:'Vamos a viajar el próximo año.'}] },
  { id:'salud6', nombre:'Salud y nutrición', emoji:'🍎', oa:'Salud y alimentación',
    intro:'Eat healthy food!',
    palabras:[{en:'healthy',es:'saludable',e:'💪'},{en:'exercise',es:'ejercicio',e:'🏋️'},{en:'sleep',es:'dormir',e:'😴'},{en:'sick',es:'enfermo',e:'🤒'},{en:'medicine',es:'medicina',e:'💊'},{en:'vegetables',es:'verduras',e:'🥦'},{en:'sugar',es:'azúcar',e:'🍬'},{en:'water',es:'agua',e:'💧'}],
    frases:[{en:'I eat healthy food.',es:'Como comida saludable.'},{en:'You should drink water.',es:'Deberías tomar agua.'}] },
  { id:'paises6', nombre:'Países y nacionalidades', emoji:'🌍', oa:'Países y nacionalidades',
    intro:"I'm Chilean. He's from Brazil.",
    palabras:[{en:'Chile / Chilean',es:'Chile / chileno',e:'🇨🇱'},{en:'Argentina',es:'Argentina',e:'🇦🇷'},{en:'Brazil / Brazilian',es:'Brasil / brasileño',e:'🇧🇷'},{en:'the USA / American',es:'EE.UU. / estadounidense',e:'🇺🇸'},{en:'England / English',es:'Inglaterra / inglés',e:'🏴󠁧󠁢󠁥󠁮󠁧󠁿'},{en:'country',es:'país',e:'🗺️'},{en:'language',es:'idioma',e:'💬'},{en:'flag',es:'bandera',e:'🚩'}],
    frases:[{en:"I'm from Chile. I'm Chilean.",es:'Soy de Chile. Soy chileno.'},{en:'She speaks two languages.',es:'Ella habla dos idiomas.'}] },
  { id:'tecnologia6', nombre:'Tecnología', emoji:'💻', oa:'Tecnología cotidiana',
    intro:'I use a computer.',
    palabras:[{en:'computer',es:'computador',e:'💻'},{en:'phone',es:'teléfono',e:'📱'},{en:'internet',es:'internet',e:'🌐'},{en:'screen',es:'pantalla',e:'🖥️'},{en:'keyboard',es:'teclado',e:'⌨️'},{en:'headphones',es:'audífonos',e:'🎧'},{en:'message',es:'mensaje',e:'💬'},{en:'game',es:'juego',e:'🎮'}],
    frases:[{en:'I use my phone to study.',es:'Uso mi teléfono para estudiar.'},{en:'Turn off the computer.',es:'Apaga el computador.'}] },
  { id:'ambiente6', nombre:'El medio ambiente', emoji:'🌳', oa:'Cuidado del medio ambiente',
    intro:'We should recycle.',
    palabras:[{en:'recycle',es:'reciclar',e:'♻️'},{en:'trash',es:'basura',e:'🗑️'},{en:'plant',es:'planta',e:'🌱'},{en:'tree',es:'árbol',e:'🌳'},{en:'river',es:'río',e:'🏞️'},{en:'ocean',es:'océano',e:'🌊'},{en:'clean',es:'limpiar',e:'🧹'},{en:'pollution',es:'contaminación',e:'🏭'}],
    frases:[{en:'We recycle paper and plastic.',es:'Reciclamos papel y plástico.'},{en:'Save water!',es:'¡Ahorra agua!'}] },
  { id:'comparativos6', nombre:'Comparativos', emoji:'⚖️', oa:'Comparar (bigger, taller…)',
    intro:'An elephant is bigger than a cat.',
    palabras:[{en:'big / bigger',es:'grande / más grande',e:'🐘'},{en:'small / smaller',es:'pequeño / más pequeño',e:'🐁'},{en:'tall / taller',es:'alto / más alto',e:'📏'},{en:'fast / faster',es:'rápido / más rápido',e:'🏎️'},{en:'good / better',es:'bueno / mejor',e:'👍'},{en:'happy / happier',es:'feliz / más feliz',e:'😄'},{en:'than',es:'que (comparación)',e:'⚖️'}],
    frases:[{en:'A car is faster than a bike.',es:'Un auto es más rápido que una bicicleta.'},{en:'This book is better.',es:'Este libro es mejor.'}] }
]
};
